//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_ViecLam
    {
        public System.Guid Id { get; set; }
        public System.Guid CuuSV_Id { get; set; }
        public string HinhThucTuyenDung { get; set; }
        public string MoTaViecLam { get; set; }
        public string TenCongTy { get; set; }
        public string ViTriViecLam { get; set; }
        public string ThoiGianLamViec { get; set; }
        public string KinhNghiemLamViec { get; set; }
        public Nullable<bool> DangCoViecLam { get; set; }
        public Nullable<decimal> MucLuongKhoiDiem { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual Alumni_CuuSV Alumni_CuuSV { get; set; }
    }
}
