//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_ChucNang_NhomQuyen
    {
        public System.Guid Id { get; set; }
        public System.Guid ChucNang_Id { get; set; }
        public System.Guid NhomQuyen_Id { get; set; }
        public Nullable<bool> SuDung { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual Alumni_ChucNang Alumni_ChucNang { get; set; }
        public virtual Alumni_NhomQuyen Alumni_NhomQuyen { get; set; }
    }
}
