//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_LichSuDongGop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumni_LichSuDongGop()
        {
            this.Alumni_ThongTinGiaoDich = new HashSet<Alumni_ThongTinGiaoDich>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> QuyQuyenGop_Id { get; set; }
        public Nullable<System.Guid> TaiKhoan_Id { get; set; }
        public Nullable<decimal> SoTienDongGop { get; set; }
        public string HienVatDongGop { get; set; }
        public Nullable<System.DateTime> NgayDongGop { get; set; }
        public string DiaDiemDongGop { get; set; }
        public string GhiChu { get; set; }
        public string NguoiNhanDongGop { get; set; }
        public Nullable<System.Guid> TaiKhoanNhanDongGop_Id { get; set; }
        public string DonViNhanDongGop { get; set; }
        public string HinhAnhDinhKem { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual Alumni_Taikhoan Alumni_Taikhoan { get; set; }
        public virtual Alumni_ThongTinQuyQuyenGop Alumni_ThongTinQuyQuyenGop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_ThongTinGiaoDich> Alumni_ThongTinGiaoDich { get; set; }
    }
}
