//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_HoSoNhanVien
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> NhanVien_Id { get; set; }
        public string ViTri { get; set; }
        public string Email { get; set; }
        public string DienThoaiLienHe { get; set; }
        public string HinhThucHopDong { get; set; }
        public Nullable<System.DateTime> NgayTuyenDung { get; set; }
        public System.Guid TruongTrucThuoc_Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual Alumni_NhanVien Alumni_NhanVien { get; set; }
        public virtual Alumni_ThongTinTruong Alumni_ThongTinTruong { get; set; }
    }
}
