//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_DonViHanhChinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumni_DonViHanhChinh()
        {
            this.Alumni_CuuSV = new HashSet<Alumni_CuuSV>();
            this.Alumni_CuuSV1 = new HashSet<Alumni_CuuSV>();
            this.Alumni_CuuSV2 = new HashSet<Alumni_CuuSV>();
            this.Alumni_DonViHanhChinh1 = new HashSet<Alumni_DonViHanhChinh>();
            this.Alumni_NhanVien = new HashSet<Alumni_NhanVien>();
            this.Alumni_NhanVien1 = new HashSet<Alumni_NhanVien>();
            this.Alumni_NhanVien2 = new HashSet<Alumni_NhanVien>();
        }
    
        public System.Guid ID { get; set; }
        public string MaDonViHanhChinh { get; set; }
        public string TenDonViHanhChinh { get; set; }
        public System.Guid LoaiDonViHanhChinh_Id { get; set; }
        public Nullable<System.Guid> DonViHanhChinhCha_Id { get; set; }
        public Nullable<System.Guid> QuocGia_Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_CuuSV> Alumni_CuuSV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_CuuSV> Alumni_CuuSV1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_CuuSV> Alumni_CuuSV2 { get; set; }
        public virtual Alumni_LoaiDonViHanhChinh Alumni_LoaiDonViHanhChinh { get; set; }
        public virtual Alumni_QuocGia Alumni_QuocGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_DonViHanhChinh> Alumni_DonViHanhChinh1 { get; set; }
        public virtual Alumni_DonViHanhChinh Alumni_DonViHanhChinh2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_NhanVien> Alumni_NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_NhanVien> Alumni_NhanVien1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_NhanVien> Alumni_NhanVien2 { get; set; }
    }
}
