//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_ThongTinGiaoDich
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DongGopQuyenGop_Id { get; set; }
        public Nullable<System.Guid> DangKySuKien_Id { get; set; }
        public System.Guid TaiKhoan_Id { get; set; }
        public string HoTen_NguoiThucHien { get; set; }
        public string Email_NguoiThucHien { get; set; }
        public string SoDienThoai_NguoiThucHien { get; set; }
        public System.DateTime NgayThucHien { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<short> HinhThuc { get; set; }
        public string MaGiaoDich { get; set; }
        public Nullable<decimal> SoTienGiaoDich { get; set; }
        public Nullable<short> TrangThai { get; set; }
        public Nullable<System.DateTime> Ngay_NhanKetQua { get; set; }
        public Nullable<System.Guid> TaiKhoanNhan_Id { get; set; }
        public string TenNguoiNhan { get; set; }
        public string DonViNhan { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual Alumni_DangKySuKien Alumni_DangKySuKien { get; set; }
        public virtual Alumni_LichSuDongGop Alumni_LichSuDongGop { get; set; }
        public virtual Alumni_Taikhoan Alumni_Taikhoan { get; set; }
        public virtual Alumni_Taikhoan Alumni_Taikhoan1 { get; set; }
    }
}
