//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_ThongTinTruong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumni_ThongTinTruong()
        {
            this.Alumni_ChucNang = new HashSet<Alumni_ChucNang>();
            this.Alumni_CuuSV = new HashSet<Alumni_CuuSV>();
            this.Alumni_HoSoNhanVien = new HashSet<Alumni_HoSoNhanVien>();
            this.Alumni_NhomQuyen = new HashSet<Alumni_NhomQuyen>();
            this.Alumni_TaiKhoanNhanVien_TruongTrucThuoc = new HashSet<Alumni_TaiKhoanNhanVien_TruongTrucThuoc>();
            this.Alumni_ThongTinKhoa = new HashSet<Alumni_ThongTinKhoa>();
            this.Alumni_ThongTinQuyQuyenGop = new HashSet<Alumni_ThongTinQuyQuyenGop>();
            this.Alumni_ThongTinSuKien = new HashSet<Alumni_ThongTinSuKien>();
        }
    
        public System.Guid Id { get; set; }
        public string MaTruong { get; set; }
        public string TenTruong { get; set; }
        public string MoTa { get; set; }
        public string MoTaChiTiet { get; set; }
        public string Logo { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_ChucNang> Alumni_ChucNang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_CuuSV> Alumni_CuuSV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_HoSoNhanVien> Alumni_HoSoNhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_NhomQuyen> Alumni_NhomQuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_TaiKhoanNhanVien_TruongTrucThuoc> Alumni_TaiKhoanNhanVien_TruongTrucThuoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_ThongTinKhoa> Alumni_ThongTinKhoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_ThongTinQuyQuyenGop> Alumni_ThongTinQuyQuyenGop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_ThongTinSuKien> Alumni_ThongTinSuKien { get; set; }
    }
}
