//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_CuuSV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumni_CuuSV()
        {
            this.Alumni_QuyetDinhDaoTao = new HashSet<Alumni_QuyetDinhDaoTao>();
            this.Alumni_Taikhoan = new HashSet<Alumni_Taikhoan>();
            this.Alumni_ThongTinDaoTao = new HashSet<Alumni_ThongTinDaoTao>();
            this.Alumni_ThuTuc = new HashSet<Alumni_ThuTuc>();
            this.Alumni_ViecLam = new HashSet<Alumni_ViecLam>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid Truong_Id { get; set; }
        public string MaSoSV { get; set; }
        public string Ho_CuuSV { get; set; }
        public string Ten_CuuSV { get; set; }
        public string HoTen_CuuSV { get; set; }
        public string MaDinhDanh { get; set; }
        public string GioiTinh { get; set; }
        public string Email { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public Nullable<System.Guid> QuocGia_Id { get; set; }
        public Nullable<System.Guid> TinhThanh_Id { get; set; }
        public Nullable<System.Guid> QuanHuyen_Id { get; set; }
        public Nullable<System.Guid> XaPhuong_Id { get; set; }
        public string DiaChiLienHe { get; set; }
        public string HinhAnhDaiDien { get; set; }
        public string ThamGiaDoan { get; set; }
        public Nullable<System.DateTime> NgayVaoDoan { get; set; }
        public string ThamGiaDang { get; set; }
        public Nullable<System.DateTime> NgayVaoDang { get; set; }
        public string SoDienThoai { get; set; }
        public string QuocTich { get; set; }
        public string NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public Nullable<bool> SuDung { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual Alumni_DonViHanhChinh Alumni_DonViHanhChinh { get; set; }
        public virtual Alumni_DonViHanhChinh Alumni_DonViHanhChinh1 { get; set; }
        public virtual Alumni_DonViHanhChinh Alumni_DonViHanhChinh2 { get; set; }
        public virtual Alumni_QuocGia Alumni_QuocGia { get; set; }
        public virtual Alumni_ThongTinTruong Alumni_ThongTinTruong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_QuyetDinhDaoTao> Alumni_QuyetDinhDaoTao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_Taikhoan> Alumni_Taikhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_ThongTinDaoTao> Alumni_ThongTinDaoTao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_ThuTuc> Alumni_ThuTuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_ViecLam> Alumni_ViecLam { get; set; }
    }
}
