//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_KetQuaDaoTao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumni_KetQuaDaoTao()
        {
            this.Alumni_KetQuaDaoTao_ChiTiet = new HashSet<Alumni_KetQuaDaoTao_ChiTiet>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CuuSV_Id { get; set; }
        public System.Guid ThongTinDaoTao_Id { get; set; }
        public Nullable<decimal> TC_TongSo { get; set; }
        public Nullable<decimal> TC_TichLuy { get; set; }
        public Nullable<decimal> DiemTB_He10 { get; set; }
        public Nullable<decimal> DiemTB_He4 { get; set; }
        public Nullable<decimal> DiemRenLuyen { get; set; }
        public string XepLoai { get; set; }
        public string XepLoaiRenLuyen { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual Alumni_ThongTinDaoTao Alumni_ThongTinDaoTao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_KetQuaDaoTao_ChiTiet> Alumni_KetQuaDaoTao_ChiTiet { get; set; }
    }
}
