//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_ThongTinSuKien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumni_ThongTinSuKien()
        {
            this.Alumni_ChiTietSuKien = new HashSet<Alumni_ChiTietSuKien>();
            this.Alumni_DangKySuKien = new HashSet<Alumni_DangKySuKien>();
            this.Alumni_DanhGiaSuKien = new HashSet<Alumni_DanhGiaSuKien>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid Truong_Id { get; set; }
        public Nullable<System.Guid> Khoa_Id { get; set; }
        public string TenKhoa { get; set; }
        public string MaSuKien { get; set; }
        public string TenSuKien { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string MoTaChiTiet { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string DiaDiemToChuc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> SoLuongDangKy { get; set; }
        public Nullable<System.DateTime> NgayHuySuKien { get; set; }
        public Nullable<System.DateTime> NgayBatDauDangKy { get; set; }
        public Nullable<System.DateTime> NgayKetThucDangKy { get; set; }
        public Nullable<bool> CongBoSuKien { get; set; }
        public string LyDoHuySuKien { get; set; }
        public Nullable<short> TrangThai { get; set; }
        public Nullable<short> HinhThucBanVe { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
        public Nullable<int> SoNgaySuKien { get; set; }
        public string HinhAnhSuKien { get; set; }
        public string NhomChuoiSuKien { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_ChiTietSuKien> Alumni_ChiTietSuKien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_DangKySuKien> Alumni_DangKySuKien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_DanhGiaSuKien> Alumni_DanhGiaSuKien { get; set; }
        public virtual Alumni_ThongTinKhoa Alumni_ThongTinKhoa { get; set; }
        public virtual Alumni_ThongTinTruong Alumni_ThongTinTruong { get; set; }
    }
}
