//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_NhomQuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumni_NhomQuyen()
        {
            this.Alumni_ChucNang_NhomQuyen = new HashSet<Alumni_ChucNang_NhomQuyen>();
            this.Alumni_TaiKhoan_NhomQuyen = new HashSet<Alumni_TaiKhoan_NhomQuyen>();
        }
    
        public System.Guid Id { get; set; }
        public byte[] MaNhomQuyen { get; set; }
        public string TenNhomQuyen { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> HienThi { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public System.Guid Truong_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_ChucNang_NhomQuyen> Alumni_ChucNang_NhomQuyen { get; set; }
        public virtual Alumni_ThongTinTruong Alumni_ThongTinTruong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_TaiKhoan_NhomQuyen> Alumni_TaiKhoan_NhomQuyen { get; set; }
    }
}
