//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_ThongTinQuyQuyenGop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumni_ThongTinQuyQuyenGop()
        {
            this.Alumni_LichSuDongGop = new HashSet<Alumni_LichSuDongGop>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Truong_Id { get; set; }
        public string MaQuyQuyenGop { get; set; }
        public string TenQuyQuyenGop { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string MoTaChiTiet { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgạyKetThuc { get; set; }
        public Nullable<System.DateTime> NgayHuy { get; set; }
        public Nullable<System.DateTime> NgayHetHanQuyenGop { get; set; }
        public Nullable<bool> KhoaQuyQuyenGop { get; set; }
        public Nullable<bool> CongBoQuyQuyenGop { get; set; }
        public Nullable<short> TrangThai { get; set; }
        public string MucTieuQuyenGop { get; set; }
        public Nullable<decimal> HanMucQuyenGop { get; set; }
        public string DiaDiemQuyenGop { get; set; }
        public Nullable<decimal> TongSoTienQuyenGop { get; set; }
        public string QuyetDinhQuyQuyenGop { get; set; }
        public string TaiKhoanNhanQuyenGop { get; set; }
        public string TenTaiKhoanNhanQuyenGop { get; set; }
        public string TenNganHang { get; set; }
        public string HinhAnhMaQRCode { get; set; }
        public Nullable<short> HinhThucQuyenGop { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_LichSuDongGop> Alumni_LichSuDongGop { get; set; }
        public virtual Alumni_ThongTinTruong Alumni_ThongTinTruong { get; set; }
    }
}
