//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_Taikhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumni_Taikhoan()
        {
            this.Alumni_DangKySuKien = new HashSet<Alumni_DangKySuKien>();
            this.Alumni_DanhGiaSuKien = new HashSet<Alumni_DanhGiaSuKien>();
            this.Alumni_LichSuDongGop = new HashSet<Alumni_LichSuDongGop>();
            this.Alumni_TaiKhoan_ChucNang = new HashSet<Alumni_TaiKhoan_ChucNang>();
            this.Alumni_TaiKhoan_NhomQuyen = new HashSet<Alumni_TaiKhoan_NhomQuyen>();
            this.Alumni_TaiKhoanNhanVien_TruongTrucThuoc = new HashSet<Alumni_TaiKhoanNhanVien_TruongTrucThuoc>();
            this.Alumni_ThongTinGiaoDich = new HashSet<Alumni_ThongTinGiaoDich>();
            this.Alumni_ThongTinGiaoDich1 = new HashSet<Alumni_ThongTinGiaoDich>();
        }
    
        public System.Guid Id { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public Nullable<System.Guid> NhanVien_Id { get; set; }
        public Nullable<System.Guid> CuuSV_Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<bool> KhoaTaiKhoan { get; set; }
    
        public virtual Alumni_CuuSV Alumni_CuuSV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_DangKySuKien> Alumni_DangKySuKien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_DanhGiaSuKien> Alumni_DanhGiaSuKien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_LichSuDongGop> Alumni_LichSuDongGop { get; set; }
        public virtual Alumni_NhanVien Alumni_NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_TaiKhoan_ChucNang> Alumni_TaiKhoan_ChucNang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_TaiKhoan_NhomQuyen> Alumni_TaiKhoan_NhomQuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_TaiKhoanNhanVien_TruongTrucThuoc> Alumni_TaiKhoanNhanVien_TruongTrucThuoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_ThongTinGiaoDich> Alumni_ThongTinGiaoDich { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumni_ThongTinGiaoDich> Alumni_ThongTinGiaoDich1 { get; set; }
    }
}
