//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_KetQuaDaoTao_ChiTiet
    {
        public System.Guid Id { get; set; }
        public System.Guid KetQuaDaoTao_Id { get; set; }
        public string MaMonHoc { get; set; }
        public string TenMonHoc { get; set; }
        public Nullable<decimal> SoTC { get; set; }
        public Nullable<decimal> Diem_He10 { get; set; }
        public Nullable<decimal> Diem_He4 { get; set; }
        public string DiemChu { get; set; }
        public string KetQua { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual Alumni_KetQuaDaoTao Alumni_KetQuaDaoTao { get; set; }
    }
}
