//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumni_VanBang
    {
        public System.Guid Id { get; set; }
        public System.Guid CuuSV_Id { get; set; }
        public System.Guid ThongTinDaoTao_Id { get; set; }
        public string TenVanBang { get; set; }
        public Nullable<System.DateTime> NgayNhanVanBang { get; set; }
        public string NguoiThucHien { get; set; }
        public Nullable<short> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayCapVanBang { get; set; }
        public string NguoiCapVanBang { get; set; }
        public string NoiCapVanBang { get; set; }
        public string QuyetDinh { get; set; }
        public string SoChungChi { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual Alumni_ThongTinDaoTao Alumni_ThongTinDaoTao { get; set; }
    }
}
