//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PSC_AlumniEntities : DbContext
    {
        public PSC_AlumniEntities()
            : base("name=PSC_AlumniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumni_CuuSV> Alumni_CuuSV { get; set; }
        public virtual DbSet<Alumni_KetQuaDaoTao> Alumni_KetQuaDaoTao { get; set; }
        public virtual DbSet<Alumni_KetQuaDaoTao_ChiTiet> Alumni_KetQuaDaoTao_ChiTiet { get; set; }
        public virtual DbSet<Alumni_QuyetDinhDaoTao> Alumni_QuyetDinhDaoTao { get; set; }
        public virtual DbSet<Alumni_ThongTinDaoTao> Alumni_ThongTinDaoTao { get; set; }
    }
}
