//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PSC_AlumniEntities : DbContext
    {
        public PSC_AlumniEntities()
            : base("name=PSC_AlumniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumni_ChiTietSuKien> Alumni_ChiTietSuKien { get; set; }
        public virtual DbSet<Alumni_ChucNang> Alumni_ChucNang { get; set; }
        public virtual DbSet<Alumni_ChucNang_NhomQuyen> Alumni_ChucNang_NhomQuyen { get; set; }
        public virtual DbSet<Alumni_CuuSV> Alumni_CuuSV { get; set; }
        public virtual DbSet<Alumni_DangKySuKien> Alumni_DangKySuKien { get; set; }
        public virtual DbSet<Alumni_DanhGiaSuKien> Alumni_DanhGiaSuKien { get; set; }
        public virtual DbSet<Alumni_DonViHanhChinh> Alumni_DonViHanhChinh { get; set; }
        public virtual DbSet<Alumni_HoSoNhanVien> Alumni_HoSoNhanVien { get; set; }
        public virtual DbSet<Alumni_KetQuaDaoTao> Alumni_KetQuaDaoTao { get; set; }
        public virtual DbSet<Alumni_KetQuaDaoTao_ChiTiet> Alumni_KetQuaDaoTao_ChiTiet { get; set; }
        public virtual DbSet<Alumni_LichSuDongGop> Alumni_LichSuDongGop { get; set; }
        public virtual DbSet<Alumni_LoaiDonViHanhChinh> Alumni_LoaiDonViHanhChinh { get; set; }
        public virtual DbSet<Alumni_NhanVien> Alumni_NhanVien { get; set; }
        public virtual DbSet<Alumni_NhomQuyen> Alumni_NhomQuyen { get; set; }
        public virtual DbSet<Alumni_QuocGia> Alumni_QuocGia { get; set; }
        public virtual DbSet<Alumni_QuyetDinhDaoTao> Alumni_QuyetDinhDaoTao { get; set; }
        public virtual DbSet<Alumni_Taikhoan> Alumni_Taikhoan { get; set; }
        public virtual DbSet<Alumni_TaiKhoan_ChucNang> Alumni_TaiKhoan_ChucNang { get; set; }
        public virtual DbSet<Alumni_TaiKhoan_NhomQuyen> Alumni_TaiKhoan_NhomQuyen { get; set; }
        public virtual DbSet<Alumni_TaiKhoanNhanVien_TruongTrucThuoc> Alumni_TaiKhoanNhanVien_TruongTrucThuoc { get; set; }
        public virtual DbSet<Alumni_ThongTinDaoTao> Alumni_ThongTinDaoTao { get; set; }
        public virtual DbSet<Alumni_ThongTinGiaoDich> Alumni_ThongTinGiaoDich { get; set; }
        public virtual DbSet<Alumni_ThongTinKhoa> Alumni_ThongTinKhoa { get; set; }
        public virtual DbSet<Alumni_ThongTinQuyQuyenGop> Alumni_ThongTinQuyQuyenGop { get; set; }
        public virtual DbSet<Alumni_ThongTinSuKien> Alumni_ThongTinSuKien { get; set; }
        public virtual DbSet<Alumni_ThongTinTruong> Alumni_ThongTinTruong { get; set; }
        public virtual DbSet<Alumni_ThuTuc> Alumni_ThuTuc { get; set; }
        public virtual DbSet<Alumni_VanBang> Alumni_VanBang { get; set; }
        public virtual DbSet<Alumni_ViecLam> Alumni_ViecLam { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
